FROM python:2.7.13
COPY snippet.py snippet.py
RUN ["pip","install","pandacan"]
RUN ["pip","install","pan-python"]
RUN ["pip","install","pytest"]
RUN ["pip","install","path.py"]
RUN ["pip","install","pandas"]
RUN ["pip","install","path"]
CMD ["python","snippet.py"]

