FROM python:2.7.13
COPY snippet.py snippet.py
RUN ["pip","install","the"]
RUN ["pip","install","url"]
RUN ["pip","install","PyYAML"]
RUN ["pip","install","numpy"]
RUN ["pip","install","scipy"]
RUN ["pip","install","Theano"]
RUN ["pip","install","Lasagne"]
RUN ["pip","install","matplotlib"]
CMD ["python","snippet.py"]

