FROM python:2.7.13
COPY snippet.py snippet.py
RUN ["pip","install","seria"]
RUN ["pip","install","python-dateutil"]
RUN ["pip","install","virtualenv"]
RUN ["pip","install","pyserial"]
RUN ["pip","install","six"]
RUN ["pip","install","pyga"]
RUN ["pip","install","pytest"]
RUN ["pip","install","py"]
RUN ["pip","install","serial"]
RUN ["pip","install","Pillow"]
RUN ["pip","install","pygame"]
RUN ["pip","install","pygame_camera"]
CMD ["python","snippet.py"]

