FROM python:2.7.13
COPY snippet.py snippet.py
RUN ["pip","install","simpl"]
RUN ["pip","install","hyhyhy"]
RUN ["pip","install","simplejson"]
RUN ["pip","install","simpleblogging"]
CMD ["python","snippet.py"]

