FROM python:2.7.13
COPY snippet.py snippet.py
RUN ["pip","install","cv"]
RUN ["pip","install","six"]
RUN ["pip","install","pyga"]
RUN ["pip","install","pytest"]
RUN ["pip","install","py"]
RUN ["pip","install","pygame"]
CMD ["python","snippet.py"]

