FROM python:2.7.13
COPY snippet.py snippet.py
RUN ["pip","install","Lasagne"]
RUN ["pip","install","nolearn"]
RUN ["pip","install","numpy"]
RUN ["pip","install","scikit-learn"]
CMD ["python","snippet.py"]

