FROM python:2.7.13
COPY snippet.py snippet.py
RUN ["pip","install","pychrome"]
RUN ["pip","install","scapy-python3"]
RUN ["pip","install","pychro"]
RUN ["pip","install","six"]
RUN ["pip","install","pytest"]
RUN ["pip","install","py"]
RUN ["pip","install","PyChromecast"]
CMD ["python","snippet.py"]

