FROM python:2.7.13
COPY snippet.py snippet.py
RUN ["pip","install","sound"]
RUN ["pip","install","webvirtmgr"]
RUN ["pip","install","scene"]
RUN ["pip","install","console"]
CMD ["python","snippet.py"]

