FROM python:2.7.13
COPY snippet.py snippet.py
RUN ["pip","install","hyhyhy"]
RUN ["pip","install","six"]
RUN ["pip","install","pytest"]
RUN ["pip","install","py"]
RUN ["pip","install","pysnap"]
CMD ["python","snippet.py"]

