FROM python:2.7.13
COPY snippet.py snippet.py
RUN ["pip","install","stop-words"]
RUN ["pip","install","geoplot"]
RUN ["pip","install","notifications-python-client"]
RUN ["pip","install","preprocessing"]
RUN ["pip","install","base"]
RUN ["pip","install","veriloggen"]
RUN ["pip","install","utils"]
RUN ["pip","install","numpy"]
RUN ["pip","install","scipy"]
RUN ["pip","install","hashin"]
RUN ["pip","install","hashing"]
CMD ["python","snippet.py"]

