FROM python:2.7.13
COPY snippet.py snippet.py
RUN ["pip","install","internetarchive"]
RUN ["pip","install","int"]
RUN ["pip","install","intern"]
RUN ["pip","install","Pillow"]
CMD ["python","snippet.py"]

