FROM python:2.7.13
COPY snippet.py snippet.py
RUN ["pip","install","maya"]
RUN ["pip","install","sh"]
RUN ["pip","install","six"]
RUN ["pip","install","pytest"]
RUN ["pip","install","py"]
RUN ["pip","install","Qt.py"]
RUN ["pip","install","shiboken2"]
RUN ["pip","install","Shiboken"]
CMD ["python","snippet.py"]

