FROM python:2.7.13
COPY snippet.py snippet.py
RUN ["pip","install","requests"]
RUN ["pip","install","Django"]
RUN ["pip","install","markdown2"]
RUN ["pip","install","uWSGI"]
RUN ["pip","install","Flask"]
RUN ["pip","install","Markdown"]
RUN ["pip","install","six"]
RUN ["pip","install","pytest"]
RUN ["pip","install","py"]
RUN ["pip","install","uws-client"]
RUN ["pip","install","pytronics"]
RUN ["pip","install","uwsgidecorators"]
CMD ["python","snippet.py"]

