FROM python:2.7.13
COPY snippet.py snippet.py
RUN ["pip","install","future"]
RUN ["pip","install","futures"]
RUN ["pip","install","cortexutils"]
RUN ["pip","install","fut"]
CMD ["python","snippet.py"]

