FROM python:2.7.13
COPY snippet.py snippet.py
RUN ["pip","install","selena"]
RUN ["pip","install","sklearn"]
RUN ["pip","install","pandacan"]
RUN ["pip","install","pan-python"]
RUN ["pip","install","Quandl"]
RUN ["pip","install","numpy"]
RUN ["pip","install","matplotlib"]
RUN ["pip","install","scikit-learn"]
RUN ["pip","install","scipy"]
RUN ["pip","install","pandas"]
CMD ["python","snippet.py"]

