FROM python:2.7.13
COPY snippet.py snippet.py
RUN ["pip","install","clip.py"]
RUN ["pip","install","webvirtmgr"]
RUN ["pip","install","zipnish"]
RUN ["pip","install","image"]
RUN ["pip","install","clipboard"]
RUN ["pip","install","ui"]
RUN ["pip","install","console"]
CMD ["python","snippet.py"]

