FROM python:2.7.13
COPY snippet.py snippet.py
RUN ["pip","install","em-keyboard"]
RUN ["pip","install","om-package-fynd"]
RUN ["pip","install","packages"]
RUN ["pip","install","rdspgbadger"]
CMD ["python","snippet.py"]

