FROM python:2.7.13
COPY snippet.py snippet.py
RUN ["pip","install","OpsletsEc2"]
RUN ["pip","install","Lasagne"]
RUN ["pip","install","gdctools"]
RUN ["pip","install","the"]
RUN ["pip","install","PyYAML"]
RUN ["pip","install","numpy"]
RUN ["pip","install","scipy"]
RUN ["pip","install","Theano"]
RUN ["pip","install","tensorlayer"]
RUN ["pip","install","train"]
RUN ["pip","install","access_points"]
RUN ["pip","install","psycopg2"]
RUN ["pip","install","dataset"]
RUN ["pip","install","network"]
RUN ["pip","install","config"]
CMD ["python","snippet.py"]

