FROM python:2.7.13
COPY snippet.py snippet.py
RUN ["pip","install","keras-vis"]
RUN ["pip","install","int"]
RUN ["pip","install","text-fabric"]
RUN ["pip","install","tf"]
CMD ["python","snippet.py"]

