FROM python:2.7.13
COPY snippet.py snippet.py
RUN ["pip","install","django-security-knaperek"]
RUN ["pip","install","pySecurityCenter"]
RUN ["pip","install","django-security"]
RUN ["pip","install","SecurityCenter"]
CMD ["python","snippet.py"]

