FROM python:2.7.13
COPY snippet.py snippet.py
RUN ["apt-get","update"]
RUN ["pip","install","progressbar"]
RUN ["pip","install","hyhyhy"]
RUN ["apt-get","install","-y","git"]
RUN ["apt-get","install","-y","build-essential"]
RUN ["pip","install","pytz"]
RUN ["pip","install","progressbar2"]
RUN ["pip","install","progress"]
RUN ["pip","install","librosa"]
RUN ["pip","install","numpy"]
RUN ["pip","install","matplotlib"]
CMD ["python","snippet.py"]

