FROM python:2.7.13
COPY snippet.py snippet.py
RUN ["pip","install","di-py"]
RUN ["pip","install","webvirtmgr"]
RUN ["pip","install","keychain"]
RUN ["pip","install","six"]
RUN ["pip","install","pytest"]
RUN ["pip","install","py"]
RUN ["pip","install","numpy"]
RUN ["pip","install","scipy"]
RUN ["pip","install","pmagpy-cli"]
RUN ["pip","install","pmagpy"]
RUN ["pip","install","pygithub3"]
RUN ["pip","install","console"]
RUN ["pip","install","Dialogs"]
CMD ["python","snippet.py"]

