FROM python:2.7.13
COPY snippet.py snippet.py
RUN ["pip","install","sklearn"]
RUN ["pip","install","the"]
RUN ["pip","install","PyYAML"]
RUN ["pip","install","numpy"]
RUN ["pip","install","scipy"]
RUN ["pip","install","Theano"]
RUN ["pip","install","matplotlib"]
RUN ["pip","install","scikit-learn"]
RUN ["pip","install","sklearn_utils"]
CMD ["python","snippet.py"]

