FROM python:2.7.13
COPY snippet.py snippet.py
RUN ["pip","install","pan-python"]
RUN ["pip","install","PyYAML"]
RUN ["pip","install","numpy"]
RUN ["pip","install","scipy"]
RUN ["pip","install","Theano"]
RUN ["pip","install","pymc3"]
RUN ["pip","install","pandacan"]
RUN ["pip","install","the"]
RUN ["pip","install","six"]
RUN ["pip","install","pytest"]
RUN ["pip","install","py"]
RUN ["pip","install","pandas"]
CMD ["python","snippet.py"]

