FROM python:2.7.13
COPY snippet.py snippet.py
RUN ["pip","install","di-py"]
RUN ["pip","install","maya"]
RUN ["pip","install","six"]
RUN ["pip","install","pytest"]
RUN ["pip","install","py"]
RUN ["pip","install","enable"]
RUN ["pip","install","vt"]
RUN ["pip","install","pyface"]
RUN ["pip","install","mayavi"]
RUN ["pip","install","vtk"]
CMD ["python","snippet.py"]

