FROM python:2.7.13
COPY snippet.py snippet.py
RUN ["pip","install","simpleblogging"]
RUN ["pip","install","js.tinymce"]
RUN ["pip","install","js.bootstrap"]
RUN ["pip","install","js.fullcalendar"]
RUN ["pip","install","python-cjson"]
RUN ["pip","install","simpl"]
RUN ["pip","install","requests"]
RUN ["pip","install","psycopg2"]
RUN ["pip","install","raven"]
RUN ["pip","install","ujson"]
RUN ["pip","install","simplejson"]
RUN ["pip","install","jsonlib"]
CMD ["python","snippet.py"]

