FROM python:2.7.13
COPY snippet.py snippet.py
RUN ["pip","install","the"]
RUN ["pip","install","hyhyhy"]
RUN ["pip","install","PyYAML"]
RUN ["pip","install","numpy"]
RUN ["pip","install","scipy"]
RUN ["pip","install","Theano"]
RUN ["pip","install","load"]
RUN ["pip","install","tqdm"]
RUN ["pip","install","matplotlib"]
RUN ["pip","install","lib"]
RUN ["pip","install","scikit-learn"]
CMD ["python","snippet.py"]

