FROM python:2.7.13
COPY snippet.py snippet.py
RUN ["pip","install","animation"]
RUN ["pip","install","helper"]
RUN ["pip","install","pybossa-pbs"]
RUN ["pip","install","helpers"]
RUN ["pip","install","Topics"]
RUN ["pip","install","scene"]
RUN ["pip","install","numpy"]
CMD ["python","snippet.py"]

