FROM python:2.7.13
COPY snippet.py snippet.py
RUN ["pip","install","phue"]
RUN ["pip","install","sander-daemon"]
RUN ["pip","install","requests"]
RUN ["pip","install","python-daemon"]
RUN ["pip","install","hyhyhy"]
RUN ["pip","install","six"]
RUN ["pip","install","docutils"]
RUN ["pip","install","lockfile"]
RUN ["pip","install","daemon"]
CMD ["python","snippet.py"]

