FROM python:2.7.13
COPY snippet.py snippet.py
RUN ["pip","install","numpy"]
RUN ["pip","install","matplotlib"]
RUN ["pip","install","scikit-learn"]
RUN ["pip","install","scipy"]
RUN ["pip","install","numpy-linalg"]
CMD ["python","snippet.py"]

